name: first workflow
on:
  workflow_dispatch:
    inputs:
      versionName:
        required: true
        description: "this is version Name for github workflow"
  # repository_dispatch:
  #   types: [test]
  # push:
  #   branches:
  #     - "main"
  # pull_request:
  #   branches:
  #     - "feature"
  #   types: [opened, closed]
jobs:
  first-workflow-job:
    name: first job
    runs-on: ubuntu-latest
    steps:
      - name: before checkout
        run: ls
        shell: bash

      - name: checkout steps
        uses: actions/checkout@v4

      - name: after checkout 
        run: ls
        shell: bash
