name: first workflow
on:
  push:
    branches:
      - "main"
jobs:
  first-workflow-job:
    name: first job
    runs-on: ubuntu-latest
    steps:
      - name: before checkout
        run: ls
        shell: bash

      - name: checkout steps
        uses: actions/checkout@v4

      - name: after checkout 
        run: ls
        shell: bash
